force-app/main/default/objects/Application_Potential__c/Application_Potential__c.object-meta.xml
<CustomObject>
    <description>Based on Industry Application Potentials Data</description>
    <label>Application Potential</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Potential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Potentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Potential__c/fields/Cleaners__c.field-meta.xml
<CustomField>
    <fullName>Cleaners__c</fullName>
    <label>Cleaners</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Functional_Coatings__c.field-meta.xml
<CustomField>
    <fullName>Functional_Coatings__c</fullName>
    <label>Functional Coatings</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Instant_Adhesives__c.field-meta.xml
<CustomField>
    <fullName>Instant_Adhesives__c</fullName>
    <label>Instant Adhesives</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Machinery_Adhesives__c.field-meta.xml
<CustomField>
    <fullName>Machinery_Adhesives__c</fullName>
    <label>Machinery Adhesives</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Potting_Impregnation__c.field-meta.xml
<CustomField>
    <fullName>Potting_Impregnation__c</fullName>
    <label>Potting &amp; Impregnation</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Protective_Coatings__c.field-meta.xml
<CustomField>
    <fullName>Protective_Coatings__c</fullName>
    <label>Protective Coatings</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Sealing__c.field-meta.xml
<CustomField>
    <fullName>Sealing__c</fullName>
    <label>Sealing</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/Structural_Bonding__c.field-meta.xml
<CustomField>
    <fullName>Structural_Bonding__c</fullName>
    <label>Structural Bonding</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Potential__c/fields/TYPICAL_DEVICES__c.field-meta.xml
<CustomField>
    <fullName>TYPICAL_DEVICES__c</fullName>
    <label>TYPICAL DEVICES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testApplicationComponent.cls
@isTest
public class testApplicationComponent 
{
     @isTest
     public static void testmethod1()
     {
         Contact cnt=new Contact();
         cnt.lastname='test';
         cnt.Industry__c='testindustry';
         insert cnt;
         
         Application_Potential__c app=new Application_Potential__c();
         app.Cleaners__c=12;
         app.Industry__c='testindustry';
         app.Equipment__c=10;
         app.Functional_Coatings__c=20;
         app.Instant_Adhesives__c=2;
         app.Machinery_Adhesives__c=6;
         app.Potting_Impregnation__c=3;
         app.Sealing__c=10;
         app.Structural_Bonding__c=45;
         app.Protective_Coatings__c=0;
         app.TYPICAL_DEVICES__c='test record';   
         insert app;
        // applicationPotentialcontroller.wrapperClassforCoverageReport wrp=new applicationPotentialcontroller.wrapperClassforCoverageReport();
         applicationPotentialcontroller.getapplicationPotential(cnt.Id,'Contact');
             
             
     }
}