force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/trg_Account__c.field-meta.xml
<CustomField>
    <fullName>trg_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>trg_Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/test_trg_Account.cls
@isTest
public class test_trg_Account 
{
    @istest
	public static void testMethod1()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.trg_Account__c=True;
        Insert mc;
        Account acc = New Account();
        acc.Name='TestIndustryCode1';
        acc.Industry='BANKING';
        Insert acc;
       // System.assertEquals(NULL,acc.Industry_Code__c);
        
    }
    public static void testMethod2()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.trg_Account__c=True;
        Insert mc;
        Account acc = New Account();
        acc.Name='TestIndustryCode1';
        //acc.Industry='BANKING';
        Insert acc;
        
    }
}