force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/IsQuotationTrgActivated__c.field-meta.xml
<CustomField>
    <fullName>IsQuotationTrgActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger Name : trg_Quotation</description>
    <label>IsQuotationTrgActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Salesforce Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>Approver_Email__c</fullName>
    <label>Approver Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Contact_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Contact_Pincode__c</fullName>
    <formula>Customer_Contact__r.MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test_trg_Quotation.cls
@istest
public class test_trg_Quotation {
    
    @istest
    public static void testQuotemethod()
    {
        EcomAPI__c mc=new EcomAPI__c();
        mc.IsQuotationTrgActivated__c=true;
        insert mc;
        
        Quotation__c q=new Quotation__c();
        //q.CC_Status__c='';
        q.Approver_Email__c='ram@test.com';
        q.Comments__c='dfgd';
        q.Total_Price__c=120.00;
        insert q;
       
        contact con=new contact();
        con.LastName='Shinde';
        con.MailingPostalCode='400001';
        con.Prospect_Interest_Type__c='Quotation';
        insert con;
         q.Customer_Contact__c=con.id;
        update q;
        
        Product__c pr=new Product__c();
        pr.SKU__c='AD.GA.195902';
        pr.Quotation__c=q.id;
        pr.Quantity__c='10';
        insert pr;
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile',IB_SKU__c='AD.GA.195902',IDH__c='AD.GA.195902',isactive=true);
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);
        
        
        //Create the PricebookEntry
        	PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
          
        );
        Insert pbe;
          q.CC_Status__c='mql';
        // q.Contact_Pincode__c='343';
        update q;
       
    }
     @istest
    public static void testQuotemethodtwo()
    {
        EcomAPI__c mc=new EcomAPI__c();
        mc.IsQuotationTrgActivated__c=true;
        insert mc;
        
        Quotation__c q=new Quotation__c();
        //q.CC_Status__c='';
        q.Approver_Email__c='ram@test.com';
        q.Comments__c='dfgd';
        q.Total_Price__c=120.00;
        insert q;
       
        lead le=new lead();
        le.LastName='Shinde';
        le.PostalCode='400001';
        le.Prospect_Interest_Type__c='Quotation';
        le.Company='Nanostuffs';
        insert le;
         q.Lead_Name__c=le.id;
        update q;
        Product__c pr=new Product__c();
        pr.SKU__c='AD.GA.195902';
        pr.Quotation__c=q.id;
        pr.Quantity__c='10';
        insert pr;
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile',IB_SKU__c='AD.GA.195902',IDH__c='AD.GA.195902',isactive=true);
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);
        
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
          
        );
        Insert pbe;
        
        
        
        Opportunity opp=new Opportunity();
        opp.name='test';
        opp.amount=100;
        opp.CloseDate=system.today();
        opp.StageName='closed Won';
        Insert opp;
        
        OpportunityLineItem oppl =new OpportunityLineItem();
        oppl.UnitPrice=10;
        oppl.Product2Id=pro.id;
        oppl.OpportunityId=opp.id;
        oppl.PricebookEntryId=pbe.id;
        oppl.Quantity=5;
        insert oppl;
        
        
          q.CC_Status__c='mql';
        // q.Contact_Pincode__c='343';
        update q;
       
    }
}