force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/IsecomordertrgActivated__c.field-meta.xml
<CustomField>
    <fullName>IsecomordertrgActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Apex Trigger : trg_onOrderAfterUpdate</description>
    <label>IsoldecomordertrgActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/IndustryBuying_Status__c.field-meta.xml
<CustomField>
    <fullName>IndustryBuying_Status__c</fullName>
    <label>IndustryBuying Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/PlaceEmail__c.field-meta.xml
<CustomField>
    <fullName>PlaceEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PlaceEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/test_trg_onOrderAfterUpdate.cls
@isTest
public class test_trg_onOrderAfterUpdate 
{
    @isTest
    public static void testMethos1()
    {
        EcomAPI__c mc=new EcomAPI__c();
        mc.IsecomordertrgActivated__c=true;
        insert mc;
            
		Order_Information__c ord =new Order_Information__c();
    	ord.Name='123456';
       	Insert ord;
        ord.IndustryBuying_Status__c='Confirmed';
        ord.Payment_Status__c ='Order Placed';
        ord.PlaceEmail__c=false;
        update ord;
    }
}