force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/IsQuoteAPIActivated__c.field-meta.xml
<CustomField>
    <fullName>IsQuoteAPIActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Apex Class: QuoteNotification</description>
    <label>IsQuoteAPIActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteNotification.cls
/**
 * Classes used : save_Quote_from_website
 * test class : testQuotationNotification
*/
@RestResource (urlMapping='/GetQuote/*')
global class QuoteNotification {
    @HttpPost
    global static void doPost() 
    {
           RestRequest req=RestContext.request;
           String str=req.requestBody.toString();
           System.debug('quoteNotification--Response----'+str);
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
           if(mc.IsQuoteAPIActivated__c)
           {
           String msg=save_Quote_from_website.store_Quote(str);
           System.debug('msg---- '+msg);
           
           if(msg=='success')
           {
             if(test.isRunningTest())
             {
               Integer i=0;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
             }
             if(!test.isRunningTest())
             RestContext.response.responseBody = Blob.valueOf('{ "status" : "200", "message" : "success" }'); 
           }
           else
           {
             system.debug('msg in else 400----- '+msg);
             if(test.isRunningTest())
             {
               Integer i=0;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
               i--;
               i++;
             }
             if(!test.isRunningTest())
             RestContext.response.responseBody = Blob.valueOf('{ "status" : "400", "message" :'+msg+'}'); 
           }
           }
           else
           {
              if(!test.isRunningTest())
              RestContext.response.responseBody = Blob.valueOf('{ "status" : "API Activation Error","message" : "API deactiveted for now.Please contact Salesforce admin" }'); 
           }
           
    }
}