force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/IsneworderTrgActivated__c.field-meta.xml
<CustomField>
    <fullName>IsneworderTrgActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger Name :Trg_onEcomOrderAfterUpdate</description>
    <label>IsneworderTrgActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/Billing_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Billing_Pincode__c</fullName>
    <label>Pincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Pincode__c</fullName>
    <label>Pincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Trg_onEcomOrderAfterUpdateTestClass.cls
@isTest
public class Trg_onEcomOrderAfterUpdateTestClass {
 
    @isTest
    public static void testOrderStatusUpdate()
    {
       EcomAPI__c mc =new EcomAPI__c();
       mc.IsneworderTrgActivated__c=true;
       insert mc;
       Order_Information__c ord = New Order_Information__c();
       ord.Name='1234';
       ord.Shipping_Pincode__c='400006';
       ord.Payment_Status__c='Order Placed';
       ord.Billing_Pincode__c='201001';
       insert ord;
       ord.Payment_Status__c='RTO';
       ord.Payment_Status__c='delivered';
       update ord;
    }
}