force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/Confirmed_Order__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>IB Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testOrderConfirmationtrigger.cls
@isTest
public class testOrderConfirmationtrigger 
{
    @isTest
	public static void testMethod1()
    {
       Test.setMock(HttpCalloutMock.class, new orderConfirmationMockcalloutClass());
       Order_Information__c ord=new Order_Information__c();
       ord.Order_Number__c='107202706';
       ord.Payment_Status__c='Booked';
       Insert ord;
        
       ord.Confirmed_Order__c=true;
       update ord;
    }
}