force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/bulk_discount__c.field-meta.xml
<CustomField>
    <fullName>bulk_discount__c</fullName>
    <label>Bulk Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/CodCharge__c.field-meta.xml
<CustomField>
    <fullName>CodCharge__c</fullName>
    <label>CodCharge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Intro_Discount__c.field-meta.xml
<CustomField>
    <fullName>Intro_Discount__c</fullName>
    <label>Intro Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Charge__c</fullName>
    <label>Shipping Charge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Pincode__c</fullName>
    <label>Pincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Total Logical CP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <inlineHelpText>Total Payable Amount including cod and shipping charge.</inlineHelpText>
    <label>Total Payable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/Ordered_Product__c.object-meta.xml
<CustomObject>
    <label>Ordered Product</label>
    <nameField>
        <label>Item Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordered_Product__c/fields/Bulk_Discount__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Discount__c</fullName>
    <label>Bulk Discount</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/CodCharge__c.field-meta.xml
<CustomField>
    <fullName>CodCharge__c</fullName>
    <label>COD - Charge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Coupon_Discount__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Discount__c</fullName>
    <label>Promotional Discount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Order_Information__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/image_url__c.field-meta.xml
<CustomField>
    <fullName>image_url__c</fullName>
    <label>Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Intro_Discount__c.field-meta.xml
<CustomField>
    <fullName>Intro_Discount__c</fullName>
    <label>Intro Discount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Order_Information__c.field-meta.xml
<CustomField>
    <fullName>Order_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Information</label>
    <referenceTo>Order_Information__c</referenceTo>
    <relationshipLabel>Ordered Products</relationshipLabel>
    <relationshipName>Ordered_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Item Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Quanitity__c.field-meta.xml
<CustomField>
    <fullName>Quanitity__c</fullName>
    <label>Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <formula>Order_Information__r.Shipping_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <formula>Order_Information__r.Shipping_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Shipping_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Pincode__c</fullName>
    <formula>Order_Information__r.Shipping_Pincode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State__c</fullName>
    <formula>Order_Information__r.Shipping_State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Striked_Off_Price__c.field-meta.xml
<CustomField>
    <fullName>Striked_Off_Price__c</fullName>
    <label>Unit Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Tax_Inclusive_Price__c.field-meta.xml
<CustomField>
    <fullName>Tax_Inclusive_Price__c</fullName>
    <label>Total Price(Inc Tax And Discount)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Tax_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Tax_Percentage__c</fullName>
    <label>Tax Percentage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutClassTest.cls
@isTest(seeAllData=true)
private class CalloutClassTest {
     @isTest static void testCallout() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse res = CalloutClass.getInfoFromExternalService();
        LinkedlnWebinarCallout.calloutWebservice('piyusha122@testing.com','8111111234','Linkedin','test','compa','14526','test','0-20');         
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = res.getBody();
        String expectedValue = '{"example":"test"}';
        //System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }
    
    /* @isTest static void testCallouttwo() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
         HttpResponse res = CalloutClass.shipment();
         Order_Information__c o=new Order_Information__c();
         o.Name='2010';
         o.Email__c='ramji.shinde@nanostuffs.com';
        	insert o;
         Ordered_Product__c op=new Ordered_Product__c();
         op.Name='test';
         op.Order_Information__c=o.Id;
         op.Order_Status__c='Order delivered';
         op.SKU__c='AD.RE.195910';
         insert op;
     //   list<Order_Information__c> oplist=[select id,Order_Status__c,CodCharge__c,Shipping_City__c,Shipping_State__c,Shipping_Pincode__c,Shipping_Address__c,Price__c, Total__c ,image_url__c, SKU__c,Tax_Inclusive_Price__c,Quanitity__c,Name,Shipping_Charge__c,Tax_Percentage__c,Intro_Discount__c,Bulk_Discount__c,Coupon_Discount__c,Tax__c,Subtotal__c,Striked_Off_Price__c  from Ordered_Product__c where Order_Information__c=:O.id limit 1];
         Ordered_Product__c op1=new Ordered_Product__c();
         op1.Name='test';
         op1.Order_Information__c=o.Id;
         op1.Order_Status__c='Order shipped';
         op.SKU__c='AD.GA.195892';
         insert op1;
          Order_Information__c OI=new Order_Information__c();
         test.startTest();
        ShipmentNotificationDataIntegration s=new ShipmentNotificationDataIntegration();
         s.getShipmentDetails('2010');  
         s.OrderDispatch(o);
         s.OrderDelivered(o);
         s.cover();
         ////////////////////////
         RestRequest req = new RestRequest(); 
         RestResponse res1 = new RestResponse();
         req.requestURI = '/services/apexrest/shipped_order'; 
         req.params.put('order_id', '2010');
         req.httpMethod = 'POST';
         req.addHeader('Content-Type', 'application/json'); 
         RestContext.request = req;
         RestContext.response = res1;
         ShipmentNotification.doPost('2010');
         test.stopTest();
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = res.getBody();
        String expectedValue = '{"response":{"shipped_count":2,"delivered_count":0,"product_shipped":[{"product_name":"Loctite 609 - 50 ml","product_sku":"AD.RE.195910"},{"product_name":"Loctite 518 - 50 ml","product_sku":"AD.GA.195892"}],"product_delivered":[]}}';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
    }*/
}