force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ecomOrdersAssignmentTestClass.cls
@isTest
public class ecomOrdersAssignmentTestClass 
{
    @IsTest
    public static void testecomassignment(){
        Order_Information__c ord = New Order_Information__c();
        ord.Name = '124654';
        ord.Payment_Status__c='booked';
        ord.CreatedDate=system.today()-2;
        insert ord;
        
        Order_Information__c ord1 = New Order_Information__c();
        ord1.Name = '124654';
        ord1.Payment_Status__c='booked';
        ord1.CreatedDate=system.today()-4;
        insert ord1;
        
        Test.startTest();
        ecomOrdersAssignment ecom = new ecomOrdersAssignment();
        String sch = '0 0 23 * * ?';
        system.schedule('ecomOrdersAssignment --',sch,ecom);
        Test.stopTest();
        
        
        
    }
}