force-app/main/default/objects/Secondary_Sales_Data__c/Secondary_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Secondary Sales Data</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Sales_Data__c/fields/Dec_19__c.field-meta.xml
<CustomField>
    <fullName>Dec_19__c</fullName>
    <label>Dec-19</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Secondary_Sales_Data__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Apr-18</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Secondary_Sales_Data__c/fields/Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Sales_Data__c</fullName>
    <label>Sales Data</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor Price</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secondary_Sales_Data__c/fields/Sep_18__c.field-meta.xml
<CustomField>
    <fullName>Sep_18__c</fullName>
    <label>Sep-18</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestClass.cls
@isTest(SeeAllData=true)
public class TestClass {
    @isTest static void testFunction()
    {
        Test.startTest();
        Secondary_Sales_Data__c c = new Secondary_Sales_Data__c();    
        
        c.Dec_19__c = 1000;        
        c.Sales_Data__c = 'Value';
        c.Quantity__c = 1;
        insert c;
        c.Sales_Data__c = 'Quantity';
      //  c.Sep_18__c = 2000;
        update c;
       
        Test.stopTest();
        
    }
    
}