force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <formula>Distributor__r.FirstName + Distributor__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distributor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <formula>IF(  ISBLANK(Lead__r.PostalCode)==False ,Lead__r.PostalCode, Customer_Contact__r.MailingPostalCode )</formula>
    <label>Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor_Pincode_Mapping__c/Distributor_Pincode_Mapping__c.object-meta.xml
<CustomObject>
    <label>Distributor Pincode Mapping</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Sr.No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributor Pincode Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor_Pincode_Mapping__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <label>Distributor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/Order_Information__c.object-meta.xml
<CustomObject>
    <label>E-Com Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Com Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Information__c/fields/Billing_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Billing_Pincode__c</fullName>
    <label>Pincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Eligible_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Distributor__c</fullName>
    <label>Eligible Distributor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>DelPincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>E-Com Orders</relationshipLabel>
    <relationshipName>E_Com_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Information__c/fields/Shipping_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Pincode__c</fullName>
    <label>Pincode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EcomOrderHandler.cls
public class EcomOrderHandler {
    
    public static void order_owner_update(List<Order_Information__c> neworderlist,Map<Id,Order_Information__c> oldmaporders,Boolean isupdate)
    {
        List<User> userList=[Select id,Pin_codes__c,profileId,UserRoleId from user where UserRole.name='Inside Sales Team'];
        Map<String,id> userpincodeMap=new Map<String,id>();
        List<String> pincodeList;
        for(User u  : userList)
        {
            String pincodes=u.Pin_codes__c;
            pincodeList=new List<String>();
            if(pincodes!=null && pincodes!='')
                pincodeList=pincodes.split(',');
            for(String str :pincodeList)
            {
                userpincodeMap.put(str,u.id);  
            }
            
        }
        for(Order_Information__c ord:neworderlist)
        {
            if(ord.Payment_Status__c=='RTO delivered' || ord.Payment_Status__c=='RTO' || ord.Payment_Status__c=='Returned' || ord.Payment_Status__c=='Shipped & Returned' || ord.Payment_Status__c=='Cancelled')
            {
                if(userpincodeMap.containsKey(ord.Shipping_Pincode__c) && ord.Shipping_Pincode__c!=NULL)
                {
                    Ord.OwnerId=userpincodeMap.get(ord.Shipping_Pincode__c);
                }
                
            }
            if(ord.Payment_Status__c!=NUll && oldmaporders.get(ord.id).Payment_Status__c=='booked' && ord.Payment_Status__c=='Order Placed')
            {
                Ord.OwnerId=label.Default_IST;
            }
        }
        
        
    }
  public static void order_eligible_distributor(List<Order_Information__c> EcomPincode,Boolean isinsert)
    {
        Map<String,Distributor_Pincode_Mapping__c> DistributorMap=new Map<String,Distributor_Pincode_Mapping__c>();
        
        set<String> pincode = new set<String>();
        
        for(Order_Information__c Ecom : EcomPincode)
        {
            if(Ecom.Billing_Pincode__c != null)
            {
                pincode.add(Ecom.Billing_Pincode__c);
            }
        }
        
        if(pincode.size() > 0)
        {
            for(Distributor_Pincode_Mapping__c d: [Select Id,Distributor_Name__c,Pincode__c From Distributor_Pincode_Mapping__c where Pincode__c=: pincode])
            {
                DistributorMap.put(d.Pincode__c,d);
            }
        }
        
        for(Order_Information__c Ecom : EcomPincode)
        {
            if(DistributorMap.ContainsKey(Ecom.Billing_Pincode__c))
            {
                System.debug('In Eligible Code Handler ');
                Ecom.Eligible_Distributor__c=DistributorMap.get(Ecom.Billing_Pincode__c).Distributor_Name__c;
                
            }
        }
        
        
    }
    
    public static void cta_ordeStatus_update(List<Order_Information__c> newOrderList,Map<id,Order_Information__c> oldmap,string eventtype)
    {
        Set<Id> ctaId = new Set<Id>();
        Set<Id> opptyId = new Set<Id>();
        List<Cta__c> ctalst = new List<Cta__c>();
        List<Opportunity> oppty = new List<Opportunity>();
        
        for(Order_Information__c order : newOrderList)
        {		
            System.debug('Order information in trigger :');
            if(order.Payment_Status__c != oldmap.get(order.Id).Payment_Status__c && eventtype == 'update')
            {
                opptyId.add(Order.Project__c);
            }
            else
            {
                opptyId.add(Order.Project__c);
            }
        }
        
        if(opptyId.size() > 0)
        {
            oppty = [Select id, CTA__c from Opportunity where id =: opptyId];
        }
        
        for(Opportunity opp : oppty)
        {
            ctaId.add(opp.CTA__c);
        }
        
        if(ctaId.size() > 0)
        {
            ctalst = [Select id,Order_Status__c  from CTA__c where id in : ctaId];
        }
        
        for(Cta__c cta : ctalst)
        {
            System.debug('Order information  cta update in trigger :');
            cta.Order_Status__c = newOrderList[0].Payment_Status__c;
        }
        
        try
        {
            upsert ctalst;
        }
        catch(Exception e)
        {
            System.debug(e.getMessage());
            System.debug(e.getLineNumber());
            System.debug(e.getCause());
        }
    }
}