force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>IF( Lead__r.Company  &lt;&gt; Null,Lead__r.Company, Customer_Contact__r.Account.Name)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/CTA_stage__c.field-meta.xml
<CustomField>
    <fullName>CTA_stage__c</fullName>
    <label>CTA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data Collection Process</fullName>
            </value>
            <value>
                <fullName>Data and Intent Validation Process</fullName>
            </value>
            <value>
                <fullName>Pre-sales nurturing</fullName>
            </value>
            <value>
                <fullName>Disqualified by call center team</fullName>
            </value>
            <value>
                <fullName>Assigned to IST</fullName>
            </value>
            <value>
                <fullName>Need Follow up</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed abandoned cart</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Ecoomerce_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Ecoomerce_Qualification__c</fullName>
    <label>Ecommerce Qualification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One time eCommerce</fullName>
            </value>
            <value>
                <fullName>More value for the same products</fullName>
            </value>
            <value>
                <fullName>Additional opportunity</fullName>
            </value>
            <value>
                <fullName>More value for the same products + Additional opportunity</fullName>
            </value>
            <value>
                <fullName>Need follow-up</fullName>
            </value>
            <value>
                <fullName>Speak to IST</fullName>
            </value>
            <value>
                <fullName>Does not want to speak to IST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Expected_close_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_close_date__c</fullName>
    <label>Expected close date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Flag_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Flag_Webinar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag Webinar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>IF( Customer_Contact__r.Industry_value__c &lt;&gt; Null ,Customer_Contact__r.Industry_value__c ,TEXT( Lead__r.Industry ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/New_Existing__c.field-meta.xml
<CustomField>
    <fullName>New_Existing__c</fullName>
    <label>New/Existing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Existing customer &amp; existing application</fullName>
            </value>
            <value>
                <fullName>Existing customer &amp; new application</fullName>
            </value>
            <value>
                <fullName>New customer – competitor adhesive</fullName>
            </value>
            <value>
                <fullName>New customer – conventional method</fullName>
            </value>
            <value>
                <fullName>personal use</fullName>
            </value>
            <value>
                <fullName>Trader – Competitor adhesives</fullName>
            </value>
            <value>
                <fullName>Trader – Henkel products</fullName>
            </value>
            <value>
                <fullName>New customer – No current method</fullName>
            </value>
            <value>
                <fullName>Irrelevant Segment</fullName>
            </value>
            <value>
                <fullName>Uncconectable</fullName>
            </value>
            <value>
                <fullName>Local to Authorized distributor</fullName>
            </value>
            <value>
                <fullName>Bought from eCommerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Prospect_interest_type__c.field-meta.xml
<CustomField>
    <fullName>Prospect_interest_type__c</fullName>
    <formula>TEXT(Lead__r.Prospect_Interest_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prospect interest type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Request_Callback_Product__c.field-meta.xml
<CustomField>
    <fullName>Request_Callback_Product__c</fullName>
    <label>Request Callback Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/What_was_the_initial_enquiry__c.field-meta.xml
<CustomField>
    <fullName>What_was_the_initial_enquiry__c</fullName>
    <description>Research inputs – End customer</description>
    <inlineHelpText>Research inputs – End customer</inlineHelpText>
    <label>What was the initial enquiry?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/recordTypes/eCommerce.recordType-meta.xml
<RecordType>
    <fullName>eCommerce</fullName>
    <active>true</active>
    <label>eCommerce</label>
</RecordType>

force-app/main/default/objects/CTA__c/recordTypes/Indiamart.recordType-meta.xml
<RecordType>
    <fullName>Indiamart</fullName>
    <active>true</active>
    <label>Indiamart</label>
</RecordType>

force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/CTA_trigger__c.field-meta.xml
<CustomField>
    <fullName>CTA_trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CTA_trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/trg_onCTATestClass.cls
@isTest
public class trg_onCTATestClass 
{
    /*@isTest
    public static void testMethod1()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='Qualified';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        
        
        Insert cta;
        
        Account acc = new Account(name='test1',Industry='Banking');
        insert acc;
        Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
        insert c;
        Opportunity opp = new Opportunity(Contact2__c = c.id,AccountId = acc.id,StageName = 'Potential',CloseDate = System.today(),Name='test',CTA__c=cta.id);
        insert opp;
        
        cta.Ecoomerce_Qualification__c='One time eCommerce';
        update cta;
        /*cta.Ecoomerce_Qualification__c='Additional opportunity';
update cta;
cta.Ecoomerce_Qualification__c='More value for the same products'; 
update cta;
cta.Ecoomerce_Qualification__c='More value for the same products + Additional opportunity'; 
update cta;
        
    }*/
    
    /*@isTest
    public static void testMethod2()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='Qualified';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        
        
        Insert cta;
        
        Account acc = new Account(name='test1',Industry='Banking');
        insert acc;
        Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
        insert c;
        Opportunity opp = new Opportunity(Contact2__c = c.id,AccountId = acc.id,StageName = 'Potential',CloseDate = System.today(),Name='test',CTA__c=cta.id);
        insert opp;
        
        cta.Ecoomerce_Qualification__c='Additional opportunity';
        update cta;
        /*cta.Ecoomerce_Qualification__c='More value for the same products'; 
update cta;
cta.Ecoomerce_Qualification__c='More value for the same products + Additional opportunity'; 
update cta;
        
    }
    @isTest
    public static void testMethod3()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='Qualified';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        
        
        Insert cta;
        
        Account acc = new Account(name='test1',Industry='Banking');
        insert acc;
        Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
        insert c;
        Opportunity opp = new Opportunity(Contact2__c = c.id,AccountId = acc.id,StageName = 'Potential',CloseDate = System.today(),Name='test',CTA__c=cta.id);
        insert opp;
        
        cta.Ecoomerce_Qualification__c='Additional opportunity';
update cta;
        cta.Ecoomerce_Qualification__c='More value for the same products'; 
        update cta;
        cta.Ecoomerce_Qualification__c='More value for the same products + Additional opportunity'; 
        update cta;
        
    //}*/
    
    

	@isTest
    public static void testMethod4()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        /*Lead ld2=new lead(LastName='test',Pi__Score__c =5,Pincode_Status__c='1',company='tst cmp1',Email='ramji.shinde@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld2;
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='Qualified';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        cta.Lead__c=ld2.id;
        cta.Order_Status__c = 'delivered';
        
        
        Insert cta;
        
        Account acc = new Account(name='test1',Industry='Banking');
        insert acc;
        Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
        insert c;
        Opportunity opp = new Opportunity(Contact2__c = c.id,AccountId = acc.id,StageName = 'Potential',CloseDate = System.today(),Name='test',CTA__c=cta.id);
        insert opp;
        
        
        cta.Ecoomerce_Qualification__c='More value for the same products'; 
update cta;
        cta.Ecoomerce_Qualification__c='More value for the same products + Additional opportunity'; 
        update cta;*/
        
        
        lead l1 = new lead();
        l1.lastname = 'Unknown';
        l1.Company = 'Unknown';
        l1.email = 'testunknown@gmail.com';
        l1.Phone = '8974587878';
        l1.Flag_Webinar__c = true;
        l1.Prospect_Interest_Type__c = 'Request a callback';
        l1.Request_Callback_Product__c='loctite';
        //l1.LeadSource = 'Facebook';
        //l1.OwnerId ='0057F000005SHEvQAO';
        
        insert l1;
        
        l1.OwnerId ='0057F000005SHEvQAO';
        update l1;
        
        CTA__c cta1 = new CTA__c();
        cta1.Application__c='test';
       cta1.RecordTypeId = ctaRecordTypeId.demo;
        cta1.What_was_the_initial_enquiry__c='test';
        cta1.Lead__c=l1.id;
        insert cta1;
        
    }
    
  
    /*public static void testMethod5()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        Lead ld2=new lead(LastName='test',Pi__Score__c =5,Pincode_Status__c='1',company='tst cmp1',Email='ramji.shinde@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld2;
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='Qualified';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        cta.Lead__c=ld2.Id;
        Insert cta;
        
        //cta.CTA_stage__c='';
        //update cta;
        
        
        
        /*Account acc = new Account(name='test1',Industry='Banking');
insert acc;
Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
insert c;
Opportunity opp = new Opportunity(Contact2__c = c.id,AccountId = acc.id,StageName = 'Potential',CloseDate = System.today(),Name='test',CTA__c=cta.id);
insert opp;

cta.Ecoomerce_Qualification__c='One time eCommerce';
update cta;
        cta.Ecoomerce_Qualification__c='Additional opportunity';
update cta;
cta.Ecoomerce_Qualification__c='More value for the same products'; 
update cta;
cta.Ecoomerce_Qualification__c='More value for the same products + Additional opportunity'; 
update cta;
        
    }*/
    
    @isTest
    public static void testMethod6()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        Lead ld2=new lead(LastName='test',Pi__Score__c =5,Prospect_Interest_Type__c = 'Sample Requested',Pincode_Status__c='1',company='tst cmp1',Email='ramji.shinde@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld2;
        
        Lead ld3=new lead(LastName='test',Pi__Score__c =5,Prospect_Interest_Type__c = 'Contact us',Pincode_Status__c='1',company='tst cmp1',Email='ramji1.shinde@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld3;
        
        Lead ld4=new lead(LastName='test',Pi__Score__c =5,Prospect_Interest_Type__c = 'Webinar',Pincode_Status__c='1',company='tst cmp1',Email='ramji2.shinde2@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld4;
        
        Lead ld5=new lead(LastName='test',Pi__Score__c =5,LeadSource  = 'IndiaMart',Pincode_Status__c='1',company='tst cmp1',Email='ramji1.shinde3@nanostuffs.com',street = 'street2',PostalCode = '110021',Country = 'India',Email_Encrypted__c='hfghfghf',Webinar_Id_1__c='111',phone='9766924768',Is_Webinar_Attended1__c=false );
        insert ld5;
        
        /*Account acc = new Account(name='test1',Industry='Banking');
        insert acc;
        
        Contact c = new Contact(Lastname = 'test1',MailingPostalcode = '110002', MailingCountry='India',AccountId=acc.id,Email='test@nanostuffs.com');
        insert c;
        
        Id ecomId=Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
        CTA__c cta=new CTA__c();
        cta.Application__c='test';
        cta.RecordTypeId=ecomId;
        cta.CTA_stage__c='new';
        cta.New_Existing__c='Existing customer & new application';
        cta.What_was_the_initial_enquiry__c='test';
        cta.Expected_close_date__c=system.today();
        //cta.Lead__c=ld2.Id;
        cta.Customer_Contact__c=c.id;
        Insert cta;
        
        cta.CTA_stage__c='Qualified';
        update cta;     */   
    }
    
    @isTest
    public static void testMethod7()
    {
        EcomAPI__c mc = EcomAPI__c.getOrgDefaults();
        mc.CTA_trigger__c=true;
        Insert mc;
        
        /*Case cs = new Case();
        
        cs.SuppliedName = 'test_demo';
        cs.SuppliedEmail = 'Test@demo.com';
        //cs.ContactId = con.Id;
        cs.Origin = 'Email';
        cs.Status = 'open';
        cs.Enquiry_Type__c = 'Product/Tech Enquiry';
        
       // cs.Prospect_Interest_Type__c = 'Mail enquiry';
        
        cs.SlaStartDate = system.now() - 5;
        insert cs;
        cs.Company__c = 'demo';
        cs.Phone__c = '9898181818';
        cs.Industry__c = '2-wheeler repair';
        cs.No_of_Employees__c = '0-20';
        cs.Pin_code__c = 411046;
        cs.Prospect_Interest_Type__c = 'Mail enquiry';
        update cs;
 
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=cs.id;
        insert attach;
    	
    	List<Attachment> attachments=[select id, name from Attachment where parent.id=:cs.id];
    	System.assertEquals(1, attachments.size());
*/        
        //AssignToCreateLeadForISTTeam.CreateLeadAndAssign(cs.Id);
    }
    
}