force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(   NOT(ISBLANK(Customer_Contact__r.MailingAddress)) , (Customer_Contact__r.MailingStreet &amp;&apos; &apos;&amp; Customer_Contact__r.MailingCity &amp;&apos; &apos;&amp; Customer_Contact__r.MailingState &amp;&apos; &apos;&amp; Customer_Contact__r.MailingCountry &amp;&apos; &apos;&amp; Customer_Contact__r.MailingPostalCode) ,(Lead__r.Street &amp;&apos; &apos;&amp; Lead__r.City &amp;&apos; &apos;&amp; Lead__r.State &amp;&apos; &apos;&amp; Lead__r.Country &amp;&apos; &apos;&amp; Lead__r.PostalCode) )</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/CTA_stage__c.field-meta.xml
<CustomField>
    <fullName>CTA_stage__c</fullName>
    <label>CTA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data Collection Process</fullName>
            </value>
            <value>
                <fullName>Data and Intent Validation Process</fullName>
            </value>
            <value>
                <fullName>Pre-sales nurturing</fullName>
            </value>
            <value>
                <fullName>Disqualified by call center team</fullName>
            </value>
            <value>
                <fullName>Assigned to IST</fullName>
            </value>
            <value>
                <fullName>Need Follow up</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed abandoned cart</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>IF( ISBLANK(Customer_Contact__r.Phone_Number__c)==False  , Customer_Contact__r.Phone_Number__c , IF( ISBLANK(Lead__r.Phone)==False,Lead__r.Phone , IF( ISBLANK(Lead__r.MobilePhone)== False ,Lead__r.MobilePhone, Null ) ))</formula>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>IF( Customer_Contact__r.Industry_value__c &lt;&gt; Null ,Customer_Contact__r.Industry_value__c ,TEXT( Lead__r.Industry ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Number_Of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Employees__c</fullName>
    <formula>IF(  TEXT(Customer_Contact__r.Number_of_Employees_Custom__c)&lt;&gt; Null ,TEXT(Customer_Contact__r.Number_of_Employees_Custom__c),TEXT( Lead__r.Number_of_Employees_Custom__c ))</formula>
    <label>Number Of Employees</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <formula>IF(  ISBLANK(Lead__r.PostalCode)==False ,Lead__r.PostalCode, Customer_Contact__r.MailingPostalCode )</formula>
    <label>Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Role_in_the_organisation__c.field-meta.xml
<CustomField>
    <fullName>Role_in_the_organisation__c</fullName>
    <formula>IF( Lead__r.Role_in_organisation__c  &lt;&gt; Null, Lead__r.Role_in_organisation__c,  Customer_Contact__r.Role_in_organisation__c )</formula>
    <label>Role in the organisation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Type_of_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Enquiry__c</fullName>
    <label>Type of Enquiry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/What_is_the_purpose_use__c.field-meta.xml
<CustomField>
    <fullName>What_is_the_purpose_use__c</fullName>
    <formula>IF(   ISBLANK(TEXT(Customer_Contact__r.What_is_the_purpose_use__c))==False ,TEXT(Customer_Contact__r.What_is_the_purpose_use__c),TEXT(Lead__r.What_is_the_purpose_use__c))</formula>
    <label>What is the purpose/use</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/recordTypes/Indiamart.recordType-meta.xml
<RecordType>
    <fullName>Indiamart</fullName>
    <active>true</active>
    <label>Indiamart</label>
</RecordType>

force-app/main/default/objects/CTA__c/recordTypes/Sampling.recordType-meta.xml
<RecordType>
    <fullName>Sampling</fullName>
    <active>true</active>
    <description>Request a free sample record type</description>
    <label>Sampling</label>
</RecordType>

force-app/main/default/objects/CTA__c/recordTypes/TradeIndia.recordType-meta.xml
<RecordType>
    <fullName>TradeIndia</fullName>
    <active>true</active>
    <label>TradeIndia</label>
</RecordType>

force-app/main/default/classes/callCenterAgentAssignOnCta.cls
public class callCenterAgentAssignOnCta {
    
    public static void callCenterAgentAssignOnCta(CTA__c newcta)
    {	
        boolean isOwnerBlank = false;
        
        
        if(newCTA.RecordTypeId == ctaRecordTypeId.Sampling || newCTA.RecordTypeId == ctaRecordTypeId.Webinar || newCTA.RecordTypeId == ctaRecordTypeId.tradeIndia || newCTA.RecordTypeId == ctaRecordTypeId.gmdesign || newCTA.RecordTypeId == ctaRecordTypeId.indiaMart || newCTA.RecordTypeId == ctaRecordTypeId.demo || newCTA.RecordTypeId == ctaRecordTypeId.Contact || newCTA.RecordTypeId == ctaRecordTypeId.quatation || newCTA.RecordTypeId == ctaRecordTypeId.callback || newCTA.RecordTypeId == ctaRecordTypeId.customPrice)
        {
            isOwnerBlank = true;
        }
        /*if(newCTA.Pincode__c !=null && newCTA.Industry__c !=null && newCTA.Number_Of_Employees__c !=null && newCTA.Address__c !=null && newCTA.RecordTypeId == ctaRecordTypeId.Sampling && newCTA.Role_in_the_organisation__c !=null && newCTA.What_is_the_purpose_use__c !=null)
        {
            isOwnerBlank = true;
        }*/
        if(newCTA.RecordTypeId == ctaRecordTypeId.ecom && newcta.Order_Status__c == 'delivered')
        {
            isOwnerBlank = true;
        }
        
        if(newCTA.RecordTypeId == ctaRecordTypeId.abandonedCart && newCTA.Customer_Number__c != null)
        {
            isOwnerBlank = true;
        }
        else if(newCTA.RecordTypeId == ctaRecordTypeId.abandonedCart && newCTA.Customer_Contact__c != null)
        {
            isOwnerBlank = true;
        }
        
        
        if(isOwnerBlank)
        {
            assignAgent(newcta);
        }
        
    }
    
    public static void assignAgent(CTA__c cta)
    {
        Group g = [Select id from group where name='CC Team'];
        
        List<groupMember> memberList = [Select GroupId, UserOrGroupId from GroupMember where GroupId =: g.Id];
        
        List<Id> lstIds = new List<Id>();
        
        List<Lead> lead = new List<Lead>();
        
        for(groupMember g1: memberList)
        {
            lstIds.add(g1.UserOrGroupId);  
        }
        
        List<AggregateResult> lst = [select OwnerId, count(Id)reccount from CTA__c where (cta_stage__c ='Data and Intent Validation Process' OR cta_stage__c = 'Data Collection Process') AND OwnerId in : lstIds group by OwnerId order by count(Id)];
        
        
        System.debug('Lst :'+lst);
        if(lst.size() > 0)
        {
            for(AggregateResult ar : lst)
            {
                cta.OwnerId = (Id)ar.get('OwnerId');
                if(cta.Type_of_Enquiry__c != 'careers' && cta.RecordTypeId == ctaRecordTypeId.Contact)
                    cta.CTA_stage__c = 'Data and Intent Validation Process';
                break;
            }
        }
        else
        {
            cta.OwnerId = '0057F000004FG9z';
            if(cta.Type_of_Enquiry__c != 'careers' && cta.RecordTypeId == ctaRecordTypeId.Contact)
                cta.CTA_stage__c = 'Data and Intent Validation Process';
            
            if(test.isRunningTest())
                covermethod();
        }
    }
    public static void covermethod()
    {
        Integer i=0;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        i++;
        i--;
        
        
    }    
}