force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>Approver_Email__c</fullName>
    <description>Quotation Related</description>
    <label>Approver Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <formula>TEXT( Lead__r.CC_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Quotation Related</description>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <description>Quotation Related</description>
    <label>Coupon Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/CTA_stage__c.field-meta.xml
<CustomField>
    <fullName>CTA_stage__c</fullName>
    <label>CTA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data Collection Process</fullName>
            </value>
            <value>
                <fullName>Data and Intent Validation Process</fullName>
            </value>
            <value>
                <fullName>Pre-sales nurturing</fullName>
            </value>
            <value>
                <fullName>Disqualified by call center team</fullName>
            </value>
            <value>
                <fullName>Assigned to IST</fullName>
            </value>
            <value>
                <fullName>Need Follow up</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed abandoned cart</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Discount_Applied__c.field-meta.xml
<CustomField>
    <fullName>Discount_Applied__c</fullName>
    <description>Quotation Related</description>
    <label>Discount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Ecom_Source__c.field-meta.xml
<CustomField>
    <fullName>Ecom_Source__c</fullName>
    <formula>Lead__r.Ecom_Source__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UTM Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/GST_Price__c.field-meta.xml
<CustomField>
    <fullName>GST_Price__c</fullName>
    <description>Quotation Price</description>
    <label>GST Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>IF( Customer_Contact__r.Industry_value__c &lt;&gt; Null ,Customer_Contact__r.Industry_value__c ,TEXT( Lead__r.Industry ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <formula>Lead__r.FirstName + &apos; &apos; + Lead__r.LastName</formula>
    <label>Lead Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Product_Names__c.field-meta.xml
<CustomField>
    <fullName>Product_Names__c</fullName>
    <description>Quotation Related</description>
    <label>Product Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Prospect_interest_type__c.field-meta.xml
<CustomField>
    <fullName>Prospect_interest_type__c</fullName>
    <formula>TEXT(Lead__r.Prospect_Interest_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prospect interest type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Quote_PDF_Link__c.field-meta.xml
<CustomField>
    <fullName>Quote_PDF_Link__c</fullName>
    <description>Quotation Related</description>
    <label>Quote PDF Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/SampleRequested_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>SampleRequested_Timestamp__c</fullName>
    <label>SampleRequested-Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Charge__c</fullName>
    <description>Quotation Related</description>
    <label>Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Quotation Related</description>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Total_MRP__c.field-meta.xml
<CustomField>
    <fullName>Total_MRP__c</fullName>
    <description>Quotation Related</description>
    <label>Total MRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Total_Payable__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable__c</fullName>
    <description>Quotation</description>
    <label>Total Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Quotation Related</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Total_Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Product_Number__c</fullName>
    <description>Quotation Related</description>
    <label>Total Product Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Which_Product_Sent__c.field-meta.xml
<CustomField>
    <fullName>Which_Product_Sent__c</fullName>
    <label>Which Product Sent?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOCTITE Threadlocker 243</fullName>
            </value>
            <value>
                <fullName>LOCTITE Thread Sealants 542</fullName>
            </value>
            <value>
                <fullName>LOCTITE Retaining Compound 638</fullName>
            </value>
            <value>
                <fullName>Loctite 55</fullName>
            </value>
            <value>
                <fullName>Loctite 542</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/recordTypes/Quotation.recordType-meta.xml
<RecordType>
    <fullName>Quotation</fullName>
    <active>true</active>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/Product__c/fields/CTA__c.field-meta.xml
<CustomField>
    <fullName>CTA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CTA</label>
    <referenceTo>CTA__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Quotation_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/GST_Percentage__c.field-meta.xml
<CustomField>
    <fullName>GST_Percentage__c</fullName>
    <label>GST Percentage</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/GST_Price__c.field-meta.xml
<CustomField>
    <fullName>GST_Price__c</fullName>
    <label>GST Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Discription__c.field-meta.xml
<CustomField>
    <fullName>Product_Discription__c</fullName>
    <label>Product Discription</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_URL__c</fullName>
    <label>Product Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Salesforce Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>Approver_Email__c</fullName>
    <label>Approver Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <label>Coupon Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Discount_Applied__c.field-meta.xml
<CustomField>
    <fullName>Discount_Applied__c</fullName>
    <label>Discount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Product_Names__c.field-meta.xml
<CustomField>
    <fullName>Product_Names__c</fullName>
    <label>Product Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Quotation_Number__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Number__c</fullName>
    <label>Quotation Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Quote_PDF_Link__c.field-meta.xml
<CustomField>
    <fullName>Quote_PDF_Link__c</fullName>
    <label>Quote PDF Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Charge__c</fullName>
    <label>Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Total_MRP__c.field-meta.xml
<CustomField>
    <fullName>Total_MRP__c</fullName>
    <inlineHelpText>Maximum Retailing Price</inlineHelpText>
    <label>Total MRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Total_Payable__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable__c</fullName>
    <label>Total Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Total_Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Product_Number__c</fullName>
    <label>Total Product Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/save_Quote_from_website.cls
/**
 * created Date : 02/01/2020
 * created By : Akshay Phatak
 * Wrapper Class: quoteResponse
 * Test Class : testQuotationNotification
*/
public class save_Quote_from_website 
{

    public static Set<String> productSkewIds=new Set<String>();
    public static Map<String,Product2> prodMap = new  Map<String,Product2>();
    public static Map<String,OpportunityLineItem> opplineItemMap=new Map<String,OpportunityLineItem>();
    public static Map<String,pricebookentry> pricebookEntryMap=new Map<String,pricebookentry>();
    public static List<Quotation__c> quoteListtoUpdate=new List<Quotation__c>();
    public static string store_Quote(String jsonString)
    {
      try
      {
          List<quoteResponse> responseList=(List<quoteResponse>)system.JSON.deserialize(jsonString,List<quoteResponse>.class);
          String emailAddress=responseList[0].user_contact_detail.email;
          if(emailAddress=='' || emailAddress==null)
          {
             return 'Email cant be empty'; 
          }
          //get Product Details here
          
        /*for(quoteResponse.product_infoWrapper productObj :responseList[0].quotation.product_info)
        {
            productSkewIds.add(productObj.sku);
        }
        System.debug('productSkewIds---- '+productSkewIds);
        Map<Id,Product2> productMap=new Map<Id,Product2>();
        for(Product2 prod :  [SELECT IB_SKU__c,Id FROM Product2 where IB_SKU__c IN: productSkewIds and IsActive=true])
        {
            productMap.put(prod.id,prod);
            prodMap.put(prod.IB_SKU__c,prod);
        }
        for(OpportunityLineItem opplineItem :[select Id,Product2Id,ListPrice,UnitPrice from OpportunityLineItem where Product2.IB_SKU__c in :productSkewIds])
        {
            
            if(!opplineItemMap.containsKey(opplineItem.Product2Id))
            {
                System.debug('opplineItem Product2Id----'+opplineItem.Product2Id);
            opplineItemMap.put(productMap.get(opplineItem.Product2Id).IB_SKU__c,opplineItem);
            }
        }
        System.debug('opplineItemMap-- '+opplineItemMap);
        for(pricebookentry pr :[select Id,Product2Id,Unitprice from pricebookentry where Product2Id in : prodMap.values()])
        {
            pricebookEntryMap.put(pr.product2Id,pr); 
        }*/
          //product Details End here
          String contactorLeadId=getContactOrLeadId(responseList[0].user_contact_detail);
          System.debug('contactorLeadId--- '+contactorLeadId);
          String checkcontactorLead=contactorLeadId.substringBefore('-');
          String contactId;
          String LeadId;
          if(checkcontactorLead=='ContactID')
          {
              contactId=contactorLeadId.substringAfter('-');
          }
          else
          {
              LeadId=contactorLeadId.substringAfter('-');
          }
          String quoteID=generateQuote(contactId,LeadId,responseList[0].quotation);
          System.debug('quoteID------ '+quoteID);
          Update quoteListtoUpdate;
          return 'success';
      }
      catch(Exception e)
      {
        system.debug('e.getmessage '+e.getMessage());
        System.debug('e.getnumber '+e.getLineNumber());
        String Errormessge=e.getMessage()+e.getLineNumber();
        return Errormessge;
      }
    }
    public static String getContactOrLeadId(quoteResponse.user_contact_detailWrapper userDetails)
    {
        String email=userDetails.email;
        List<Contact> contactList=[Select id,accountId from Contact where Email=:email order by createdDate desc];
        List<Lead> LeadList=[Select id from Lead where Email=:email order by createdDate desc];
        if(contactList.size()==0 && LeadList.size()==0)
        {
           //Create new Lead here 
           Lead newLead=new Lead();
           newLead.LastName=userDetails.name;
           newLead.Email=userDetails.email;
           newLead.Company=userDetails.company;
           newLead.Phone=userDetails.phone;
           newlead.PostalCode=userDetails.pincode;
           newLead.Industry=userDetails.industry;
            newLead.promo_accept_date__c = userDetails.promo_accept_date;
            newLead.promo_accept_time__c = userDetails.promo_accept_time;
            newLead.privacy_accept_date__c = userDetails.privacy_accept_date;
            newLead.privacy_accept_time__c = userDetails.privacy_accept_time;
           newLead.Prospect_Interest_Type__c='Quotation'; 
           newLead.Flag_Quotation__c=true;
           //newLead.Role_in_organisation_IM__c=userDetails.role_in_the_organisation;
           newLead.Role_in_organisation__c=userDetails.role_in_the_organisation;
           newLead.Number_of_Employees_Custom__c=userDetails.no_of_employees;
           newLead.url_params__c=userDetails.url_params;
           newLead.Ecom_campaign__c=userDetails.utm_campaign;
           newLead.Ecom_content__c=userDetails.utm_content;
           newLead.Ecom_media__c=userDetails.utm_medium;
           newLead.Ecom_term__c=userDetails.utm_term;
           newLead.Ecom_Source__c=userDetails.utm_source;            
           //newLead.NumberOfEmployees=Integer.valueOf(userDetails.no_of_employees);
           Insert newLead;
           return 'LeadID-'+newLead.id;
        }
        else
        {
            //Check Existing Contact or Lead
           if(contactList.size()!=0)
           {
               Contact cnt=new Contact();
               cnt.Id=contactList[0].id;
               List<Account> acc=[Select id,name,Industry from account where id=: contactList[0].AccountId limit 1];
               if(acc.size()>0){
               if(acc[0]!=null && userDetails.company!=null)
               {acc[0].Name=userDetails.company;}
               if(userDetails.industry!=null)
               acc[0].Industry=userDetails.industry;
               update acc[0];
               }
               cnt.Flag_Quotation__c=true;
               cnt.LastName=userDetails.name;
               cnt.MailingPostalCode=userDetails.pincode;
               cnt.url_params__c=userDetails.url_params;
               cnt.Ecom_campaign__c=userDetails.utm_campaign;
               cnt.Ecom_content__c=userDetails.utm_content;
               cnt.Ecom_media__c=userDetails.utm_medium;
               cnt.Ecom_term__c=userDetails.utm_term;
               cnt.Ecom_Source__c=userDetails.utm_source;
               cnt.Prospect_Interest_Type__c='Quotation';
               cnt.Number_of_Employees_Custom__c=userDetails.no_of_employees;
               cnt.Industry__c=userDetails.industry;
               cnt.Role_in_organisation__c=userDetails.role_in_the_organisation;
               cnt.Phone=userDetails.phone;
               update cnt;
               return 'ContactID-'+contactList[0].id;
           }
           else if(LeadList.size()!=0)
           {
               Lead leadtoUpdate=new Lead();
               leadtoUpdate.id=LeadList[0].id;
               leadtoUpdate.Flag_Quotation__c=true;
               leadtoUpdate.LastName=userDetails.name;
               leadtoUpdate.Company=userDetails.company;
               leadtoUpdate.Phone=userDetails.phone;
               leadtoUpdate.PostalCode=userDetails.pincode;
               leadtoUpdate.Industry=userDetails.industry;
               leadtoUpdate.Prospect_Interest_Type__c='Quotation'; 
               //leadtoUpdate.Role_in_organisation_IM__c=userDetails.role_in_the_organisation;
               leadtoUpdate.Role_in_organisation__c=userDetails.role_in_the_organisation;
               leadtoUpdate.Number_of_Employees_Custom__c=userDetails.no_of_employees;
               leadtoUpdate.url_params__c=userDetails.url_params;
               leadtoUpdate.Ecom_campaign__c=userDetails.utm_campaign;
               leadtoUpdate.Ecom_content__c=userDetails.utm_content;
               leadtoUpdate.Ecom_media__c=userDetails.utm_medium;
               leadtoUpdate.Ecom_term__c=userDetails.utm_term;
               leadtoUpdate.Ecom_Source__c=userDetails.utm_source;  
               //leadtoUpdate.NumberOfEmployees=Integer.valueOf(userDetails.no_of_employees);
               Update leadtoUpdate;
               return 'LeadID-'+LeadList[0].id;
           }
            
           return null;
          
        }
        
    }
    
    public static string generateQuote(String contactId,String LeadId,quoteResponse.quotationwrapper quoteInfo)
    {
        System.debug('generateQuote-contactId---- '+contactId);
        System.debug('generateQuote-LeadId---- '+LeadId);
        Id CTArecordTypeId =Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Quotation').getRecordTypeId();
        String OpportunityID;
        Quotation__c quote=new Quotation__c();
        CTA__c quotationCTA=new CTA__c();
        quotationCTA.RecordTypeId=CTArecordTypeId;
         if(contactId!=null && contactId!='')
         {
           quote.Customer_Contact__c=contactId;
           quotationCTA.Customer_Contact__c=contactId;
           quotationCTA.CTA_stage__c='Assigned to IST';
           //List<Opportunity> oppList=[Select id,contactId,Prospect_Interest_Type__c  from Opportunity where contactID=:contactId and Prospect_Interest_Type__c='Quotation' order by createdDate desc];
           /*if(oppList.size()!=0)
           {
               OpportunityID=oppList[0].id;
               createOpportunityLineItem(oppList[0].id,quoteInfo);
               System.debug('OpportunityID----- '+OpportunityID);
           }
           else
           {
               OpportunityID=createProject(contactId,quoteInfo);
               createOpportunityLineItem(OpportunityID,quoteInfo);
               System.debug('OpportunityID---- '+OpportunityID);
           }*/
        }
         quote.Comments__c=quoteInfo.Comments;
         quote.Quotation_Number__c=Decimal.valueOf(quoteInfo.Quotation_Number);
         quote.Product_Names__c=quoteInfo.Product_Names;
         quote.Approver_Email__c=quoteInfo.approver_email;
         quote.Total_Product_Number__c=quoteInfo.Total_Product_Number;
         quote.Coupon_Code__c=quoteInfo.Coupon_Code;
         quote.Quote_PDF_Link__c=quoteInfo.Quote_PDF_Link;
         quote.Total_MRP__c=Decimal.valueOf(quoteInfo.Total_MRP);
         quote.Total_Price__c=Decimal.valueOf(quoteInfo.Total_Price);
         quote.Discount_Applied__c=Decimal.valueOf(quoteInfo.Discount_Applied);
         quote.GST_Price__c=Decimal.valueOf(quoteInfo.GST_Price);
         quote.Total__c=Decimal.valueOf(quoteInfo.Total);
         quote.Shipping_Charge__c=Decimal.valueOf(quoteInfo.Shipping_Charge);
         quote.Total_Payable__c =Decimal.valueOf(quoteInfo.Total_Payable);
        
        
        
        
        
          
         quotationCTA.Comments__c=quoteInfo.Comments;
         quotationCTA.Quotation_Number__c=Decimal.valueOf(quoteInfo.Quotation_Number);
         quotationCTA.Product_Names__c=quoteInfo.Product_Names;
         quotationCTA.Approver_Email__c=quoteInfo.approver_email;
         quotationCTA.Total_Product_Number__c=quoteInfo.Total_Product_Number;
         quotationCTA.Coupon_Code__c=quoteInfo.Coupon_Code;
         quotationCTA.Quote_PDF_Link__c=quoteInfo.Quote_PDF_Link;
         quotationCTA.Total_MRP__c=Decimal.valueOf(quoteInfo.Total_MRP);
         quotationCTA.Total_Price__c=Decimal.valueOf(quoteInfo.Total_Price);
         quotationCTA.Discount_Applied__c=Decimal.valueOf(quoteInfo.Discount_Applied);
         quotationCTA.GST_Price__c=Decimal.valueOf(quoteInfo.GST_Price);
         quotationCTA.Total__c=Decimal.valueOf(quoteInfo.Total);
         quotationCTA.Shipping_Charge__c=Decimal.valueOf(quoteInfo.Shipping_Charge);
         quotationCTA.Total_Payable__c =Decimal.valueOf(quoteInfo.Total_Payable);
         //quote.CC_Status__c='mql';
         if(OpportunityID!=null && OpportunityID!='')
         {
            quote.Opportunity__c= OpportunityID;
         }
         if(LeadId!=null && LeadId!='')
         {
             quote.Lead_Name__c=LeadId;
             quotationCTA.Lead__c=LeadId;
         }
         Insert quote;
        Insert quotationCTA;
         createQuotationProducts(quote.id,quoteInfo,quotationCTA.Id);
         QuotationsMails.sendQuotationMails(quote.Id);
        /*quote.CC_Status__c='mql';
        update quote;*/
         return quote.id;
     
    }
    public static void createQuotationProducts(String Quotationid,quoteResponse.quotationwrapper quoteInfo, String ctaid)
    {
       System.debug('I am creating QuotationProducts');
       List<Product__c> quoteProductList=new List<Product__c>();
       for(quoteResponse.product_infoWrapper productObj : quoteInfo.product_info)
        {
            Product__c quotionProduct=new Product__c();
            quotionProduct.SKU__c=productObj.sku;
            quotionProduct.Quantity__c=String.valueof(productObj.quantity);
            quotionProduct.Name = productObj.itemTitle;  
            quotionProduct.Product_Image_URL__c=productObj.image;
            quotionProduct.GST_Price__c=Decimal.valueOf(productObj.gst);
            quotionProduct.GST_Percentage__c=productObj.gstpercentage;
            quotionProduct.Unit_Price__c=Decimal.valueOf(productObj.unitprice);
            quotionProduct.Total__c=Decimal.valueOf(productObj.total);
            quotionProduct.Product_Discription__c=productObj.product_Description;
            quotionProduct.Quotation__c=Quotationid;
            quotionProduct.CTA__c=ctaid;
            quoteProductList.add(quotionProduct) ;     
         }
        System.debug('quoteProductList.size()---- '+quoteProductList.size());
        insert quoteProductList;
    }
    /*public static String createProject(String contact_ID,quoteResponse.quotationwrapper quoteInfo)
    {
        System.debug('I am creating Opportunity');
        Contact cnt=[Select id,accountid from contact where id=:contact_ID];
        Opportunity newopp=new Opportunity();
        newopp.Name='DG-AG-SU-Product-Application';
        newopp.Status__c='Active';
        newopp.Contact2__c=contact_ID;
        newopp.AccountId=cnt.AccountId;
        newopp.Prospect_Interest_Type__c='Quotation';
        newopp.StageName='Trial Scheduled/Intent to buy/Webinar attended';
        newopp.SampleRequested_Timestamp__c=system.today();
        //newopp.Which_Product_Sent__c =ct.Which_Product_Sent__c;
        newopp.CloseDate=system.today();
        insert newopp;
        return newopp.id;
    } */ 
    
    /*public static void createOpportunityLineItem(String oppId,quoteResponse.quotationwrapper quoteInfo)
    {
        System.debug('I am creating OpportunityLineItem');
        System.debug('createOpportunityLineItem--oppId '+oppId);
        List<quoteResponse.product_infoWrapper> quoteProducts=new List<quoteResponse.product_infoWrapper>();
        
        quoteProducts.addAll(quoteInfo.product_info);
        List<opportunityLineItem> oppItemList=new List<opportunityLineItem>();
        System.debug('quoteInfo.product_info------ '+quoteInfo.product_info);
        System.debug('quoteInfo.product_info size------ '+quoteInfo.product_info.size());
        for(quoteResponse.product_infoWrapper productObj : quoteInfo.product_info)
        {
            OpportunityLineItem oppItem = new OpportunityLineItem();
            oppItem.OpportunityId =oppId;
            oppItem.PricebookEntryId = pricebookEntryMap.get(prodMap.get(productObj.sku).id).id;
            //oppItem.Quantity = Decimal.valueOf(listId[p].Quanitity__c);
            System.debug('productObj.sku------ '+productObj.sku);
            System.debug('opplineItemMap-----   '+opplineItemMap);
            //if(opplineItemMap.containsKey(productObj.sku))
            oppItem.UnitPrice = pricebookEntryMap.get(prodMap.get(productObj.sku).id).unitprice;
            oppItem.Quantity=productObj.quantity;
            //oppItem.TotalPrice=100;
            oppItemList.add(oppItem);
        }        
        Insert oppItemList;
    }*/ 
    
}