force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Blue_Dart_Status__c.field-meta.xml
<CustomField>
    <fullName>Blue_Dart_Status__c</fullName>
    <label>Blue Dart Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Reference_No__c</fullName>
    <label>Reference No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Waybill_No__c.field-meta.xml
<CustomField>
    <fullName>Waybill_No__c</fullName>
    <label>Waybill No.</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAftershipTrackingCTAAPI.cls
@isTest
public class TestAftershipTrackingCTAAPI {
    
    @Testsetup
    public static void dummyDate()
    {
       CTA__c ct1 = new CTA__c();
        ct1.Waybill_No__c = 'ED757654715IN';
        ct1.Reference_No__c = '1234';
        //ct1.Customer_Contact__c = '8181858585';
        ct1.Blue_Dart_Status__c = '';
        insert ct1;
    }
    
	@isTest
    public static void trackingCTAAPI()
    {
        system.debug('Dummy Data before setmock');
          Test.setMock(HttpCalloutMock.class, new CTAHttpCalloutMockImpl());
        system.debug('Dummy Data After setmock');
       AftershipTrackingCTAAPI.sendCalloutREST();
        system.debug('Dummy Data After sendCalloutREST');
    }
}