force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/CTA_stage__c.field-meta.xml
<CustomField>
    <fullName>CTA_stage__c</fullName>
    <label>CTA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data Collection Process</fullName>
            </value>
            <value>
                <fullName>Data and Intent Validation Process</fullName>
            </value>
            <value>
                <fullName>Pre-sales nurturing</fullName>
            </value>
            <value>
                <fullName>Disqualified by call center team</fullName>
            </value>
            <value>
                <fullName>Assigned to IST</fullName>
            </value>
            <value>
                <fullName>Need Follow up</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed abandoned cart</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>IF( ISBLANK(Customer_Contact__r.Phone_Number__c)==False  , Customer_Contact__r.Phone_Number__c , IF( ISBLANK(Lead__r.Phone)==False,Lead__r.Phone , IF( ISBLANK(Lead__r.MobilePhone)== False ,Lead__r.MobilePhone, Null ) ))</formula>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Ecom_Source__c.field-meta.xml
<CustomField>
    <fullName>Ecom_Source__c</fullName>
    <formula>Lead__r.Ecom_Source__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UTM Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Indiamart_QTYPE__c.field-meta.xml
<CustomField>
    <fullName>Indiamart_QTYPE__c</fullName>
    <label>Indiamart Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact Suppliers</fullName>
            </value>
            <value>
                <fullName>PNS</fullName>
            </value>
            <value>
                <fullName>Buy Leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchOwnerAssignment.cls
global class BatchOwnerAssignment implements Database.Batchable<sObject>, Database.Stateful
{
    Exception[] errors = new Exception[0];
	global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        List<String> listownerId = new List<String>();
        listownerId.add('0057F0000011TdL');
        listownerId.add('0057F0000011Dlq');
        
        List<String> listStage = new List<String>();
        listStage.add('New');
        listStage.add('Data and Intent Validation Process');
        listStage.add('Data Collection Process');
        String query = 'SELECT Id, OwnerId, cta_stage__c, RecordTypeId, Customer_Number__c, Indiamart_QTYPE__c FROM CTA__c where ownerid =: listownerId AND cta_stage__c =: listStage AND Customer_Number__c != null AND Lead__c != null AND Indiamart_QTYPE__c != \'PNS\' AND Ecom_Source__c != \'DialB2B\' AND createddate > 2022-01-01T00:00:00z';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<CTA__c> ctalist){
        // process each batch of records
        
        for(Cta__c cta : ctalist)
        {
            if(cta.Indiamart_QTYPE__c != 'PNS' && cta.Customer_Number__c != null && cta.RecordTypeId != ctaRecordTypeId.ecom)
            {
                    cta.OwnerId = '0057F000004FGA4QAO';
            }  
        }  
        try{
            update ctalist;
            
            if(Test.isRunningTest()){
                //do something
                Exception e;
                errors.add(e);
            }
        }
        catch(Exception e)
        {
            errors.add(e);
        }
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        if(!errors.isEmpty())
        {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.toAddresses = new String[] {'aman.khurana@nanostuffs.com','pritam.shinde@nanostuffs.com'};
                message.setSubject('Exception in BatchOwnerAssignment : ') ;
            message.setPlainTextBody('BatchOwnerAssignment Failed : '+errors);
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }
    } 
}