force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/CTA_stage__c.field-meta.xml
<CustomField>
    <fullName>CTA_stage__c</fullName>
    <label>CTA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data Collection Process</fullName>
            </value>
            <value>
                <fullName>Data and Intent Validation Process</fullName>
            </value>
            <value>
                <fullName>Pre-sales nurturing</fullName>
            </value>
            <value>
                <fullName>Disqualified by call center team</fullName>
            </value>
            <value>
                <fullName>Assigned to IST</fullName>
            </value>
            <value>
                <fullName>Need Follow up</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed abandoned cart</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>IF( ISBLANK(Customer_Contact__r.Phone_Number__c)==False  , Customer_Contact__r.Phone_Number__c , IF( ISBLANK(Lead__r.Phone)==False,Lead__r.Phone , IF( ISBLANK(Lead__r.MobilePhone)== False ,Lead__r.MobilePhone, Null ) ))</formula>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Indiamart_QTYPE__c.field-meta.xml
<CustomField>
    <fullName>Indiamart_QTYPE__c</fullName>
    <label>Indiamart Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact Suppliers</fullName>
            </value>
            <value>
                <fullName>PNS</fullName>
            </value>
            <value>
                <fullName>Buy Leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Prospect_interest_type__c.field-meta.xml
<CustomField>
    <fullName>Prospect_interest_type__c</fullName>
    <formula>TEXT(Lead__r.Prospect_Interest_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prospect interest type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchOwnerAssignment_Test.cls
@istest
public class BatchOwnerAssignment_Test {
	@istest
    public static void ownerAssignmentTest()
    {
        List<lead> leadList = new List<lead>();
        for(integer i = 0; i < 100; i++)
        {
            Lead l = new Lead();
            l.LastName = 'test Name' + i;
            l.Company = 'demo' + i;
            l.Email = 'test.Name' + i + '@demo.com';
            l.Prospect_Interest_Type__c = 'Sample Requested';
            l.PostalCode = '110001';
            l.Phone = '8454841848';
            leadList.add(l);
        }
        
        insert leadList;
        
        List<cta__c> ctaList = new List<cta__c>();
        ctaList = [SELECT Id, OwnerId, cta_stage__c, RecordTypeId, Customer_Number__c, Indiamart_QTYPE__c,lead__c FROM CTA__c where lead__c =: leadList];
        
        
        for(Cta__c cta : ctaList)
        {
            cta.OwnerId = '0057F0000011TdL';
        }
        update ctaList;
        
        Test.startTest();
        BatchOwnerAssignment bc = new BatchOwnerAssignment();
        database.executeBatch(bc);
        
        ScheduleBatchOwnerAssignment sh1 = new ScheduleBatchOwnerAssignment();      
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch,sh1);
        Test.stopTest();
        
        List<cta__c> updatedCtaList = new List<cta__c>();
        updatedCtaList = [SELECT Id, OwnerId, cta_stage__c, RecordTypeId, Customer_Number__c, Indiamart_QTYPE__c,lead__c FROM CTA__c where lead__c =: leadList];
        
        integer count = 0;
        for(Cta__c cta : updatedCtaList)
        {
            if(cta.OwnerId != '0057F0000011TdL')
            {
                count = count + 1;
            }
        }
        
        System.assertEquals(100,count);
    }
}