force-app/main/default/objects/CTA__c/CTA__c.object-meta.xml
<CustomObject>
    <description>Created to capture different CTA information</description>
    <label>CTA</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>CTA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTA__c/fields/Date_Of_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Enquiry__c</fullName>
    <description>Indiamart Related</description>
    <label>Date Of Enquiry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Ecom_Source__c.field-meta.xml
<CustomField>
    <fullName>Ecom_Source__c</fullName>
    <formula>Lead__r.Ecom_Source__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UTM Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/EMAIL_ALT__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_ALT__c</fullName>
    <description>Indiamart Related</description>
    <label>EMAIL_ALT</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/ENQ_MESSAGE__c.field-meta.xml
<CustomField>
    <fullName>ENQ_MESSAGE__c</fullName>
    <description>Indiamart Related</description>
    <label>ENQ_MESSAGE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Enquiry_Message__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Message__c</fullName>
    <description>For All Types of Enquiry</description>
    <label>Enquiry Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Indiamart_ID__c.field-meta.xml
<CustomField>
    <fullName>Indiamart_ID__c</fullName>
    <externalId>true</externalId>
    <label>Indiamart ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Indiamart_QTYPE__c.field-meta.xml
<CustomField>
    <fullName>Indiamart_QTYPE__c</fullName>
    <label>Indiamart Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact Suppliers</fullName>
            </value>
            <value>
                <fullName>PNS</fullName>
            </value>
            <value>
                <fullName>Buy Leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CTAs</relationshipLabel>
    <relationshipName>CTAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Indiamart Related Field</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/fields/Time_Of_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Time_Of_Enquiry__c</fullName>
    <description>Indiamart Related</description>
    <label>Time Of Enquiry</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CTA__c/recordTypes/Indiamart.recordType-meta.xml
<RecordType>
    <fullName>Indiamart</fullName>
    <active>true</active>
    <label>Indiamart</label>
</RecordType>

force-app/main/default/objects/CTA__c/recordTypes/TradeIndia.recordType-meta.xml
<RecordType>
    <fullName>TradeIndia</fullName>
    <active>true</active>
    <label>TradeIndia</label>
</RecordType>

force-app/main/default/classes/TradeIndiaIntegration.cls
/**
* Indiamart Integration with Salesforce
* This class is scheduled for every 20 Minutes
* Created By : Pritam Shinde
* Created Date : 25/10/2021
* Created by : Pritam Shinde
*/
public class TradeIndiaIntegration implements Schedulable
{
    /*TradeIndiaIntegration testobj=new TradeIndiaIntegration();
	System.schedule('TradeIndia 0','0 0 * * * ?',testobj);*/
    
    
    static List<TradeIndiaWrapper> wrapperList;
    public TradeIndiaWrapper iObj=new TradeIndiaWrapper();
    
    public TradeIndiaIntegration()
    {
        wrapperList=new List<TradeIndiaWrapper>();
    }
    
    public void execute(SchedulableContext sc)
    {
        extract_LeadData();  
    }
    
    @future(callout=true)
    public static void extract_LeadData()
    {
        String responsebody;
        try
        {
            String userid = System.Label.TradeIndia_userid;
            String profile_id = System.label.TradeIndia_profile_id;
            String key = System.label.TradeIndia_Key;
            Datetime to_date1 = System.now();
            String to_date=to_date1.format('yyyy-MM-dd%20HH:mm:ss','Asia/Kolkata');
            System.debug('to_date1 '+to_date1);
            Datetime from_date1=to_date1.addMinutes(-60);
            String from_date=from_date1.format('yyyy-MM-dd%20HH:mm:ss','Asia/Kolkata');
            System.debug('from_date1 '+from_date1);
            HttpRequest request=new HttpRequest();
            //String endpoint ='https://www.tradeindia.com/utils/my_inquiry.html?userid='+userid+'&profile_id='+profile_id+'&key='+key+'&from_date=2021-11-26%2011:00:00&to_date=2021-11-26%2012:00:00/';
            String endpoint ='https://www.tradeindia.com/utils/my_inquiry.html?userid='+userid+'&profile_id='+profile_id+'&key='+key+'&from_date='+from_date+'&to_date='+to_date+'/';
            System.debug('endpoint '+endpoint);
            request.setEndpoint(endpoint);
            request.setMethod('POST');
            request.setTimeout(50000);
            Http http=new Http(); 
            HttpResponse response=http.send(request);
            System.debug('response '+response);
            System.debug('response Body '+response.getBody());
            responsebody=response.getbody();
            
            if(responsebody.substring(0,1)=='[')
            {
                wrapperList=(List<TradeIndiaWrapper>)JSON.deserialize(responsebody,List<TradeIndiaWrapper>.class);  
            }
            else
            {
                responsebody='['+responsebody+']';
                wrapperList=(List<TradeIndiaWrapper>)JSON.deserialize(responsebody,List<TradeIndiaWrapper>.class);  
            }
            System.debug('wrapperList '+wrapperList);
            
            List<Lead> leadList=new List<Lead>();
            List<Lead> leadUpdateList=new List<Lead>();
            List<CTA__c> ctainsert=new List<CTA__c>();
            if(wrapperList.size() > 0)   
            {   
                for(TradeIndiaWrapper obj : wrapperList)
                {
                    List<Lead> existing_LeadList=new List<Lead>();
                    
                    System.debug('obj.MOB---- '+obj.sender_mobile);
                    if(obj.sender_mobile!=null)
                    {
                        existing_LeadList=[Select id,leadsource,Company,ENQ_MESSAGE__c from lead where phone= :obj.sender_mobile order by createddate desc]; 
                    }
                    
                    System.debug('existing_LeadList---- '+existing_LeadList);
                    
                    if(existing_LeadList.size()>0)
                    {
                        Lead lObj=new Lead();
                        lObj=existing_LeadList[0];
                        
                        if(obj.address != null)
                        {
                            lobj.street = obj.address;
                            lObj.PostalCode=obj.address.substringAfterLast(',');
                        }
                        
                        if(obj.sender_name==null && (lObj.LastName==null || lObj.LastName=='NA'))
                        {
                            lObj.LastName='NA';  
                        }
                        else
                        {
                            lObj.LastName=obj.sender_name; 
                        }
                        
                        if(obj.sender_co==null && (lObj.Company==null || lObj.Company=='NA') )
                        {
                            lObj.Company='NA';  
                        }
                        else
                        {
                            lObj.Company=obj.sender_co;  
                        }
                        
                        lobj.Ecom_media__c=obj.sender_uid;
                        lObj.Indiamart_QTYPE__c=obj.inquiry_type;
                        
                        if(obj.sender_mobile != null)
                        {
                            lobj.phone = obj.sender_mobile;
                        }
                        
                        lobj.Email = obj.sender_email;
                        lobj.Subject__c = obj.subject;
                        lObj.Date_Of_Enquiry__c=obj.generated_date;
                        lobj.Time_Of_Enquiry__c=obj.generated_time;
                        lobj.State = obj.sender_state;
                        lobj.City = obj.sender_city;
                        lobj.Product_Name__c = obj.product_name;
                        lobj.Country = obj.sender_country;
                        lobj.Ecom_Source__c = obj.product_source;
                        
                        //System.debug('Is numeric quantity' +obj.quantity.isNumeric());
                        if(obj.quantity != null && obj.quantity.isNumeric())
                            lobj.Product_Quantity__c = decimal.valueOf(obj.quantity);
                        
                        if(obj.rfi_id != null)
                            lobj.Indiamart_ID__c = obj.rfi_id;
                        
                        if(lobj.ENQ_MESSAGE__c == null)
                            lobj.ENQ_MESSAGE__c = obj.message;
                        
                        if(lObj.LeadSource==null)
                            lObj.LeadSource='TradeIndia';
                        leadUpdateList.add(lObj);
                        Id recTypeId = Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('TradeIndia').getRecordTypeId();
                        CTA__c cta=new CTA__c();
                        cta.RecordTypeId=recTypeId;
                        cta.Lead__c=lObj.id;
                        cta.Indiamart_ID__c=obj.rfi_id;
                        cta.Indiamart_QTYPE__c = obj.inquiry_type;
                        cta.Subject__c = obj.subject;
                        cta.Date_Of_Enquiry__c = obj.generated_date;
                        cta.Time_Of_Enquiry__c = obj.generated_time;
                        cta.Enquiry_Message__c = obj.message;
                        cta.EMAIL_ALT__c = obj.sender_email;
                        ctainsert.add(cta);
                    }
                    else
                    {
                        Lead lObj=new Lead();
                        Lead lObjRef=new Lead();
                        lObjRef.Indiamart_ID__c = obj.rfi_id;
                        lobj.Indiamart_ID__c =obj.rfi_id;
                        lobj.Phone = obj.sender_mobile;
                        if(obj.address != null)
                        {
                            lobj.street = obj.address;
                            lObj.PostalCode=obj.address.substringAfterLast(',');
                        }
                        
                        if(obj.sender_name==null && (lObj.LastName==null || lObj.LastName=='NA'))
                        {
                            lObj.LastName='NA';  
                        }
                        else
                        {
                            lObj.LastName=obj.sender_name; 
                        }
                        
                        if(obj.sender_co==null && (lObj.Company==null || lObj.Company=='NA') )
                        {
                            lObj.Company='NA';  
                        }
                        else
                        {
                            lObj.Company=obj.sender_co;  
                        }
                        
                        lobj.Ecom_media__c=obj.sender_uid;
                        lObj.Indiamart_QTYPE__c=obj.inquiry_type;
                        
                        if(obj.sender_mobile != null)
                        {
                            lobj.phone = obj.sender_mobile;
                        }
                        
                        lobj.Email = obj.sender_email;
                        lobj.Subject__c = obj.subject;
                        lObj.Date_Of_Enquiry__c=obj.generated_date;
                        lobj.Time_Of_Enquiry__c=obj.generated_time;
                        lobj.State = obj.sender_state;
                        lobj.City = obj.sender_city;
                        lobj.Product_Name__c = obj.product_name;
                        lobj.Country = obj.sender_country;
                        lobj.Ecom_Source__c = obj.product_source;
                        
                        if(obj.quantity != null && obj.quantity.isNumeric())
                            lobj.Product_Quantity__c = decimal.valueOf(obj.quantity);
                        
                        if(obj.rfi_id != null)
                            lobj.Indiamart_ID__c = obj.rfi_id;
                        
                        if(lobj.ENQ_MESSAGE__c == null)
                            lobj.ENQ_MESSAGE__c = obj.message;
                        
                        if(lObj.LeadSource==null)
                            lObj.LeadSource='TradeIndia';
                        
                        leadList.add(lobj);  
                        
                        Id recTypeId = Schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('TradeIndia').getRecordTypeId();
                        CTA__c cta=new CTA__c();
                        cta.Lead__r= lObjRef;
                        cta.RecordTypeId=recTypeId;
                        cta.Indiamart_ID__c=obj.rfi_id;
                        cta.Indiamart_QTYPE__c = obj.inquiry_type;
                        cta.Subject__c = obj.subject;
                        cta.Date_Of_Enquiry__c = obj.generated_date;
                        cta.Time_Of_Enquiry__c = obj.generated_time;
                        cta.Enquiry_Message__c = obj.message;
                        cta.EMAIL_ALT__c = obj.sender_email;
                        ctainsert.add(cta);
                        
                    }
                }
            }
            if(leadList.size()!=0)
            {
                Insert leadList;
            }
            if(leadUpdateList.size()>0)
            {
                update leadUpdateList; 
            }
            if(ctainsert.size()>0)
            {
                    Insert ctainsert; 
            }
            
        }
        catch(Exception e)
        {
            system.debug('error'+e);
            system.debug('error'+e.getLineNumber());
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.toAddresses = new String[] {'pritam.shinde@nanostuffs.com'};
            message.setSubject('TradeIndia Error from TradeIndiaIntegration Class') ;
            message.setPlainTextBody(e.getMessage()+'--'+e.getLineNumber()+'/n'+responsebody);
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }
    }
    
}