force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Confirmation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Company_Size__c.field-meta.xml
<CustomField>
    <fullName>Company_Size__c</fullName>
    <label>Company Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MRP_inclusive_of_all_taxes__c.field-meta.xml
<CustomField>
    <fullName>MRP_inclusive_of_all_taxes__c</fullName>
    <label>MRP (inclusive of all taxes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Net_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Payable_Amount__c</fullName>
    <label>Net Payable Amount (inclusive of taxes)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
    <fullName>Offer_Product__c</fullName>
    <label>Offer Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOCTITE Threadlocker 243</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Order_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Requested_Date__c</fullName>
    <label>Order Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <label>OTP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Pincode_Status__c.field-meta.xml
<CustomField>
    <fullName>Pincode_Status__c</fullName>
    <label>Pincode Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Role_In_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Role_In_Organisation__c</fullName>
    <label>Role In Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Stauts__c.field-meta.xml
<CustomField>
    <fullName>Stauts__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Original Price(inclusive of taxes)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Total_price_after_50_discount__c.field-meta.xml
<CustomField>
    <fullName>Total_price_after_50_discount__c</fullName>
    <label>Total price(after 50% discount)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/handlerContactTrigger.cls
public class handlerContactTrigger 
{
    static List<User> userList = [SELECT id,Pin_codes__c,Email,Contact.Account.Name FROM User WHERE Profile.Name = 'Partner Community User - Custom'];
    static Map<String,user> pinCodeUserMap = new Map<String,user>();
	public static void createOffer(List<Contact> cntList)
    {
        for(User u  : userList)
        {
            if(u.Pin_codes__c!=null)
            pinCodeUserMap.put(u.Pin_codes__c,u); 
        }
        for( Contact l: cntList)
        {
                Offer__c offer = new Offer__c();
                offer.Comment__c = l.pi__comments__c;
                offer.Company_Name__c = l.Company__c;
                offer.Company_Size__c =l.Number_of_Employees_Custom__c;
                offer.Designation__c = l.title;
                offer.Email__c = l.Email;
                offer.First_Name__c = l.FirstName;
                offer.Last_Name__c = l.LastName;
                offer.GST__c = l.GST__c;
                offer.GST_Amount__c = l.GST_Amount__c;
                offer.Industry__c = l.Industry__c;
                offer.Net_Payable_Amount__c = l.Net_Payable_Amount__c;
                offer.Offer_Product__c = l.Offer_Product__c;
                offer.OTP__c = string.valueof(l.OTP__c);
                offer.Pincode_Status__c = l.Pincode_Status__c;
                offer.Role_In_Organisation__c = l.Role_in_organisation_c__c;
                offer.Quantity__c = l.Quantity__c;
                offer.Total_Amount__c = l.Total_Amount__c;
                offer.MRP_inclusive_of_all_taxes__c = l.MRP_inclusive_of_all_taxes__c;
                offer.Total_price_after_50_discount__c = l.Total_price_after_50_discount__c;
                offer.Phone__c = l.Phone;
                offer.Order_Requested_Date__c = system.today();
                offer.Stauts__c = 'Active';
                for(String s :pinCodeUserMap.keySet())
                {
                    if(l.MailingPostalCode!=null)
                    {
                        if(s!=null && s.contains (l.MailingPostalCode))   
                        {
                            offer.OwnerId=pinCodeUserMap.get(s).id; 
                        }  
                    }     
                }  
                offer.Customer_Contact__c=l.id;
                offer.Customer__c=l.AccountId;
                Insert offer;  
        }
         
    }
}