force-app/main/default/objects/Customized_Price__c/Customized_Price__c.object-meta.xml
<CustomObject>
    <label>Customized Price</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Customized Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customized Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customized_Price__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customized Prices</relationshipLabel>
    <relationshipName>Customized_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customized_Price__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Customized Prices</relationshipLabel>
    <relationshipName>Customized_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EcomAPI__c/EcomAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>All Flags</label>
</CustomObject>

force-app/main/default/objects/EcomAPI__c/fields/IsRequestCallbacktrgActivated__c.field-meta.xml
<CustomField>
    <fullName>IsRequestCallbacktrgActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger Name : trg_onRequesttoCallBack</description>
    <label>IsRequestCallbacktrgActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Salesforce Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Contact_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Contact_Pincode__c</fullName>
    <formula>Customer_Contact__r.MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Refer_Friend__c/Refer_Friend__c.object-meta.xml
<CustomObject>
    <label>Refer Friend</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refer Friends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Refer_Friend__c/fields/CC_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Status__c</fullName>
    <label>CC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>mql</fullName>
            </value>
            <value>
                <fullName>nmql</fullName>
            </value>
            <value>
                <fullName>noco</fullName>
            </value>
            <value>
                <fullName>callback</fullName>
            </value>
            <value>
                <fullName>callback1</fullName>
            </value>
            <value>
                <fullName>callback2</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Refer_Friend__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Refer Friends</relationshipLabel>
    <relationshipName>Refer_Friends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Refer_Friend__c/fields/Contact_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Contact_Pincode__c</fullName>
    <formula>Contact_Name__r.MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Refer_Friend__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Refer Friends</relationshipLabel>
    <relationshipName>Refer_Friends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request Callback</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Callback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Callbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Request Callbacks</relationshipLabel>
    <relationshipName>Request_Callbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Request Callbacks</relationshipLabel>
    <relationshipName>Request_Callbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test_trg_onRequesttoCallBack.cls
@istest
public class test_trg_onRequesttoCallBack {
     @istest
    public static void testReftofrndmethod()
    {
        EcomAPI__c mc = new EcomAPI__c();
        mc.IsRequestCallbacktrgActivated__c=true;
        Insert mc;
        
        Request__c q=new Request__c();
        //q.CC_Status__c='';
       // q.Name='ram@test.com';
       // q.SKU='dfgd';
       // q.Total_Price__c='120';
        q.Product_SKU__c='AD.GA.195902';
        insert q;
       
        contact con=new contact();
        con.LastName='Shinde';
        con.MailingPostalCode='400001';
        con.Prospect_Interest_Type__c='Quotation';
        insert con;
         q.Contact_Name__c=con.id;
        update q;
        
        
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile',IB_SKU__c='AD.GA.195902',IDH__c='AD.GA.195902',isactive=true);
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);
        
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
          
        );
        Insert pbe;
          q.CC_Status__c='mql';
        // q.Contact_Pincode__c='343';
        //update q;
       
    }
     @istest
    public static void testReftofrndmethodtwo()
    {
        EcomAPI__c mc = new EcomAPI__c();
        mc.IsRequestCallbacktrgActivated__c=true;
        Insert mc;
       Request__c q=new Request__c();
        //q.CC_Status__c='';
       // q.Name='ram@test.com';
       // q.SKU='dfgd';
       // q.Total_Price__c='120';
        q.Product_SKU__c='AD.GA.195902';
        insert q;
       
        lead le=new lead();
        le.LastName='Shinde';
        le.PostalCode='400001';
        le.Prospect_Interest_Type__c='Quotation';
        le.Company='Nanostuffs';
        insert le;
         q.Lead_Name__c=le.id;
        update q;
        
        Quotation__c quote=new Quotation__c();
        quote.lead_name__c=le.id;
        Insert quote;
        
        Customized_Price__c cpr=new Customized_Price__c();
        cpr.Lead_Name__c=le.id;
        Insert cpr;
        
        Refer_Friend__c ref=new Refer_Friend__c();
        ref.lead_name__c=le.Id;
        Insert ref;
        
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile',IB_SKU__c='AD.GA.195902',IDH__c='AD.GA.195902',isactive=true);
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);
        
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
          
        );
        Insert pbe;
          q.CC_Status__c='mql';
        // q.Contact_Pincode__c='343';
        update q;
       
    }


}